# Change baseurl before deploy
baseurl = "https://blog.chlc.cc"
languageCode = "en-us"

title = "Charlie Chiang's blog"

# Theme i18n support
# Available values: en, fr, id, ja, ko, pt-br, zh-cn, zh-tw, es, de, nl, it, th, el, uk, ar
DefaultContentLanguage = "en"

# Set hasCJKLanguage to true if DefaultContentLanguage is in [zh-cn ja ko]
# This will make .Summary and .WordCount behave correctly for CJK languages.
hasCJKLanguage = false

# Change it to your Disqus shortname before using
# disqusShortname = "charlie0129"

[pagination]
pagerSize = 5

[imaging]
# The default box filter looks like shit.
resampleFilter = "lanczos"
